name: GiWit
version: 1.0
api-version: 1.13
main: com.toguy.giwit.GiWit
author: toguy
description: Salut !

commands:
  twitch:
    usage: /<command>
    description: A test command !
  warn:
    usage: /<command>
    description: Affiche un message de warning a tous les joueurs
  alert:
    usage: /<command>
    description: Affiche un titre a tous les joueurs
  swap:
    usage: /<command>
    description: Swap les joueurs entre eux ou les inventaires
  uhc:
    usage: /<command>
    description: Gere les parametres du monde
